

-- XML DATA
-- 1. SQL Server provides a powerful platform to work with XML
--	+ XML data can be stored natively in an xml data type column
--	+ XML data can be typed according to a collection of XML schemas, or left untyped.
--	+ Support querying XML data through XQuery.
--	+ Enhancements to OPENROWSET to allow bulk loading of XML data.
--	+ The ability to parse between relational data and XML data
--	+ XML columns can be compressed and indexed.
--	+ Preserve the document order and document structure, elements and attributes values, namespace prefixes, and XML declaration.
--	+ The structure is effecient for fine-grained query like extracting some of the sections within XML document using predicate evaluation.
--	+ Effectively modifying/inserting new sections without replacing whole document, and the oprerations are performed in a transacted way.
--	+ Guarantee the XML data format by validate input with XML schemas.
--	+ Indexes on XML data type increases the query processing.
--	+ More flexible than relational structure if the structure is frequently changed.
-- 3. XML storage options:
--	+ Natively store xml data type, improves parsing speed significantly through PSVI
--	+ Using an annotated schema (AXSD) to decompose XML into columns, create a copy of XML data (called XML view) is stored at the relational level.
--	+ Data is stored as large object storage, [n]varchar(max) and varbinary(max) which create an identical copy of data.
-- 4. 