
-- TRANSACTION LOCKING AND ROW VERSIONING

-- 1. Transactions:
--	+ A transaction is a logical unit of work consisting of one or more operations.
--	+ Transactions must satisfy ACID properties:
--		- Atomicity: all operations succeed or none are applied.
--		- Consistency: ensures data integrity and adherence to constraints.
--		- Isolation: concurrent transactions execute independently without interference.
--		- Durability: once committed, changes persist even after system failures.
--	+ Transaction types:
--		- Explicit: defined with BEGIN TRANSACTION / COMMIT / ROLLBACK.
--		- Implicit: engine automatically starts a new transaction after one finishes.
--		- Batch-scoped: applies to all statements in a batch.
--		- Distributed: span multiple databases/instances, coordinated by a transaction manager.
--	+ Transactions end with COMMIT or ROLLBACK. Errors trigger automatic rollback unless handled with TRY...CATCH.

-- 2. Concurrency Control:
--	+ SQL Server uses locking and isolation levels to manage concurrent transactions.
--	+ Without control, anomalies occur:
--		- Lost updates: one update overwrites another.
--		- Dirty reads: reading uncommitted changes.
--		- Nonrepeatable reads: same row returns different values in one transaction.
--		- Phantom reads: repeated queries return new rows inserted by other transactions.
--	+ Concurrency models:
--		- Pessimistic: locks resource to prevent conflicts; best for high contention.
--		- Optimistic: reads without locks, checks for conflicts at update; best for low contention.

-- 3. Transaction Isolation levels:
--	+ Define how transactions interact with each other's changes.
--	+ Control lock acquisition, duration, and behavior when encountering modified rows.
--	+ Lower levels → more concurrency, more anomalies. Higher levels → fewer anomalies, more blocking.
--	+ Levels:
--		- READ UNCOMMITTED: allow dirty reads.
--		- READ COMMITTED (default): prevents dirty reads; nonrepeatable and phantom reads possible.
--		- REPEATABLE READ: prevents nonrepeatable reads; phantom reads possible.
--		- SERIALIZABLE: highest isolation; prevents all anomalies.
--		- RSCI (Read Committed Snapshot): statement-level consistency via row versioning.
--		- SNAPSHOT: transaction-level consistency via row versioning.
--	+ Side effects by level:
--		- READ UNCOMMITTED: Dirty, Nonrepeatable, Phantom.
--		- READ COMMITTED: nonrepeatable, Phantom.
--		- REPEATABLE READ: Phantom.
--		- SNAPSHOT / SERIALIZABLE: none.
--	+ Set isolation level with: SET TRANSACTION ISOLATION LEVEL { READ UNCOMMITTED | READ COMMITTED | REPEATABLE READ | SNAPSHOT | SERIALIZABLE }

-- 4. Locking:
--	+ Locks synchronize concurrent access to resources.
--	+ If a requested lock conflicts, the transaction waits until it is released.
--	+ Lock duration depends on isolation level and optimized locking settings.
--	+ All locks are released at transaction end.
--	+ Trade-off: fine-grained locks increase concurrency but add overhead; coarse locks reduce overhead but block more.
--	+ Best practices: minimize lock count, use snapshot isolation cautiously, batch updates/deletes to avoid escalation, ...
--	  Example: to delete 5000 rows - DELETE TOP (500) in a loop until @@ROWCOUNT = 0.

-- 5. Lock Granularity & Hierarchy:
--	+ Used to identify the type of resource to be locked.
--	+ Lock levels:
--		- RID: single row in heap.
--		- KEY: single row in B-tree.
--		- PAGE: 8 KB page.
--		- EXTENT: 8 contiguous pages.
--		- HoBT: heap or B-tree.
--		- TABLE: entire table.
--		- FILE: database file.
--		- APPLICATION: user-defined resource.
--		- METADATA: schema metadata
--		- ALLOCATION_UNIT: allocation unit.
--		- DATABASE: entire database.
--		- XACT: transaction ID (optimized locking).
--	+ Trade-off:
--		- Small granularity → more locks, higher overhead, better concurrency.
--		- Large granularity → fewer locks, lower overhead, reduced concurrency.

-- 6. Lock Modes:
--	+ Define how resources can be accessed:
--		- Shared (S): read-only; compatible with other S locks.
--		- Update (U): specify the UPLOCK hint in SELECT statement; prevents deadlocks in SELECT→UPDATE scenarios; only 1 Update lock to be granted on the resource.
--		- Exclusive (X): for modifications; blocks all except READ operations with NOLOCK/READ UNCOMMITTED.
--		- Intent (IS, IX, SIX, IU, SIU, UIX): indicate intention to lock at finer granularity; helps effectively detect conflicts at higher granular level.
--		- Schema (Sch-M, Sch-S): protect schema changes or stability.
--		- Bulk Update (BU): used with TABLOCK during bulk insert.
--		- Key-range: protects ranges of rows being read in SERIALIZABLE isolation.

-- 7. Lock Compatibility:
--	+ Determines if multiple locks can coexist on the same resource.
--	+ If a requested new lock is not compatible with existing locks, the request must wait until all incompatible locks are released or a timeout occurs.
--	+ Example compatibility matrix (Y=yes, N=no):
--		 S   U   X   IS  IX  SIX
--	 S	 Y   Y   N   Y   N   N
--	 U   Y   N   N   Y   N   N
--	 X   N   N   N   N   N   N
--	IS   Y   Y   N   Y   Y   Y
--  IX   N   N   N   Y   Y   N
-- SIX   N   N   N   Y   N   N

-- 8. Lock Escalation:
--	+ Converts many fine-grained locks into fewer coarse locks.
--	+ Reduces overhead but lowers concurrency.
--	+ Escalation examples: change intent lock to correspond full lock (IX → X at table level), escalate lower granularity to higer one (page locks → table lock).
--	+ Each escalation event operates on all locks acquired at the current statement and all previous statements within the transaction.
--	+ Triggered only if when a statement acquires ≥ 5,000 locks on a single reference of a table.
--	+ Engine checks for escalation every 1,250 new locks.
--	+ If escalation fails due to conflicts, retries after each 1,250 locks.
--	+ Optimized locking reduces the number of locks and so escalation frequency.
--	+ Monitor escalation with lock_escalation extended event.