
-- TRANSACTION LOCKING AND ROW VERSIONING
-- 1. TRANSACTION:
--	+ A transaction is a sequence of operations performed as a single logical unit of work.
--	+ A logical unit of work must exhibit ACID properties:
--		- Atomicity: either all operations within transaction are performed, or none of them are performed.
--		- Consistency: guarantees data integrity, adhere to all defined constraints, and keeps the database in valid/consistent state relative to organization's business rules at the end of transaction.
--		- Isolation: ensure concurrent transactions to work independently without interfering each other process, prevent conflicts and maintain data consistency.
--		- Durability: once a transaction is committed, its changes are permanently saved, even if the system fails.
--	+ Transaction can be controlled manually or handled automatically by system:
--		- Explicit Transactions: explicitly defined both the start and end of the transaction through an API function or by issuing the T-SQL statement (BEGIN TRANSACTION, COMMIT TRANSACTION, ROLLBACK TRANSACTION, ...).
--		- Implicit Transactions: database engine automatically starts a new transaction after other finished, this mode provides a continuous chain of transactions.
--		- Autocommit Transactions: is the default mode of the database engine, apply to every T-SQL statement, and can be overriden by either explicit or implicit transactions.
--		- Batch-scoped Transactions: applied to a batch of statements in a session.
--		- Distributed Transactions: span a transaction to other database instances, the management of the transaction must be coordinated between the resource managers by a transaction manager.
--	+ Transaction can be end by specifing COMMIT or ROLLBACK command, or is automatically rolled back by server if an error ocurrs. It is pereferred to use TRY CATCH block to manually handle errors.
--	+ 
-- 2. CONCURRENCY CONTROL:
--	+ To effectively manage concurrent transactions, SQL server provides LOCKING MECHANISM and TRANSACTION ISOLATION LEVELS.
--	+ Without concurrency control, users could see the following side effects:
--		- Lost updates: occur when two or more transactions update the same rows, the last update overwrites the other, which results in lost data.
--		- Uncommitted dependency (dirty read): occur when a transaction reads uncommitted row that's being updated by another transaction which hasn't been committed yet.
--		- Inconsistent analysis (nonrepeatable read): occur when a transaction accesses the same row several times and reads different data each time (caused by the read data is modified by other transactions).
--		- Phantom read: occur when there are multiple identical reads in the same transaction, and the later read got more data compared to earlier read (caused by other transaction insert new data within search range at a point between those reads).
--	+ Concurrency control theory has two classifications for the methods of instituting concurrency control:
--		- Pessimistic concurrency control: transactions lock requested resource, ideal in a scenario of high contention of data, where the cost of protecting data is less than the cost of resolving concurrency conflicts.
--		- Optimistic concurrency control: transactions don't lock data when they read it. But during the update operation, if the data is changed after they are read, the system will raise error and roll back. 
--		  This useful in the system where contention for data is low, and where the cost of ocassionally rolling back a transaction is lower than the cost of locking data when read.
-- 3. TRANSACTION ISOLATION LEVELS: 
--	+ Defines the degree to which one transaction must be isolated from the resource or data modifications made by other transactions.
--	+ Transaction isolation levels control:
--		- Whether locks are acquired when data is read, and what types of locks are requested.
--		- How long the read locks are held.
--		- Whether a read operation referencing rows modified by another transaction:
--			* Blocks until the exclusive lock is freed.
--			* Retrieves the committed version of the row at the time the statement or transaction started.
--			* Reads the uncommitted data modification.
--	+ A lower isolation level increases the ability of many transactions to access data at the same time, but increases the number of concurrency effects transactions might encounter.
--	+ A higher isolation level reduces the types of concurrency effects, but requires more system resources and increases the chances that one transaction blocks another.
--	+ Isolation levels (include two options that support row versioning):
--		- READ UNCOMMITTED: dirty reads are allowed, one transaction might see not-yet-committed changes made by other transactions.
--		- READ COMMITTED: is the default level, read locks are hold only during the read operation (ex: single select statement) is performed, the write lock is persist during the transaction.
--		- REPEATABLE READ: the database engine keeps read and write locks until the end of the transaction, range-locks aren't managed, phantom reads can occur.
--		- SERIALIZABLEl: the highest level where transactions are completely isolated from one another.
--		- Read Committed Snapshot (RCSI): use row versioning to provide snapshot read on each statement (statement-level read consistency), no other locks acquired on reading resource except the schema stability (Sch-S) table level locks.
--		- SNAPSHOT: use row versioning to provide transaction-level read consistency, only the schema stability (Sch-S) table locks are acquired.
--	+ Concurrency side effects ocurred by the different isolation levels (Dirty read - D, Nonrepeatable read - N, Phantom read - P):
--		- READ UNCOMMITTED: D, N, P
--		- READ COMMITTED: N, P
--		- REPEATABLE READ: P
--		- SNAPSHOT, SERIALIZABLE: none
--	+ Use T-SQL statement to set isolation level: SET TRANSACTION ISOLATION LEVEL { READ UNCOMMITTED | READ COMMITTED | REPEATABLE READ | SNAPSHOT | SERIALIZABLE }
-- 4. LOCKING:
--	+ Locking is a mechanism used to synchronize access by mutiple users to the same piece of data at the same time.
--	+ Locks have different modes, each mode define the level of dependency and compatibility level. If a transaction request a lock that conflicts with other existing locks, the request will be paused until these locks are released.
--	+ How long a transaction holds the lock depends on the transaction isolation level settings and whether or not optimized locking is enabled.
--	+ All locks held by a transaction are released when the transaction completes (either commits or rolls back).
--	+ Locks are granted and managed by lock manager, ensure no lock confliction exists.
--	+ Lock can be converted into different lock modes.
--	+ There is a trade off between locking cost and concurrency cost. Using low-level locks increases concurrency but also increase system overhead, opposite with high-level locks.
--	+ It is recommended to acquire only a small number of lock at a time, it reduces the lock memory and ocurrence of lock escalations.
--		* Ex: Use read uncommitted/ read snapshot (use with caution), enable optimized locking, limit the number of rows updated/deleted at a time (DELETE/UPDATE TOP 500 repeatedly until @@ROWCOUNT is 0)
--	==================================================
--	DECLARE @DeletedRows int;
--	WHILE @DeletedRows IS NULL OR @DeletedRows > 0
--	BEGIN
--	    DELETE TOP (500)
--	    FROM LogMessages
--	    WHERE LogDate < '2024-09-26'
--	    SELECT @DeletedRows = @@ROWCOUNT;
--	END;
--	==================================================
-- 5. LOCK GRANULARITY AND HIERARCHIES:
--	+ The Database Engine provide lock granularity to identify which type of resources to be locked.
--	+ There are multiple levels of granualarity (also called lock hierarchy):
--		- RID: lock a single row within a heap.
--		- KEY: lock a single row in a B-tree index.
--		- PAGE: an 8 kilobyte page, such as data or index pages.
--		- EXTENT: a contiguous group of eight pages.
--		- HoBT: a heap or B-tree (data or index pages) lock.
--		- TABLE: lock the entire table, including all data and indexes.
--		- FILE: a database file.
--		- APPLICATION: an application-specified resource.
--		- METADATA: metadata locks.
--		- ALLOCATION_UNIT: an allocation unit.
--		- DATABASE: the entire database.
--		- XACT: transaction ID lock used in Optimized locking.
--	+ Manually specifying lock granularity should be carefully considered of its tradeoff:
--		- number of locks: small granularity (such as row lock) requires a large number of locks, larger granualarity requires fewer locks
--			* More locks to be stored and managed result in higher overhead.
--		- concurrency ability: small granualarity restricts access to small part of table thus increase concurrency, higher granularity reduce concurrency.
-- 6. LOCK MODES:
--	+ The lock modes used to determine how the resource can be accessed:
--		- Shared (S): used for read operations such as SELECT statement, no data modification allowed on Shared lock resource, but other S lock can be granted along side.
--		- Update (U): used with UPLOCK hint to specify resources that can be updated, prevent deadlock might occur in SELECT then UPDATE format.
--		- Exclusive (X): used for data-modification operations (such as INSERT, UPDATE, or DELETE), this prevent all concurrent operations to be perfomred, except READ operation used with NOLOCK hint or the READ UNCOMMITTED isolation level.
--		- Intent: used to establish a lock hierarchy by specifying a higher granularity level (usually TABLE), improving lock management.
--			* types of intent locks are: intent shared (IS), intent exclusive (IX), shared with intent exclusive (SIX), intent update (IU), shared intent update (SIU), update intent exclusive (UIX).
--			* this lock helps the Database Engine to quickly detect lock conflicts at the higher level of granularity.
--		- Schema modification (Sch-M): used when modifying schema, to prevent any operations on the table
--		- Schema stability (Sch-S): used to prevent any schema modification.
--		- Bulk Update (BU): used when bulk copying data into a table with the TABLOCK hint.
--		- Key-range: protects the range of rows read by a query when using SERIALIZABLE transaction isolation level.
-- 7. LOCK COMPATIBILITY:
--	+ Lock compatibility controls whether multiple transactions can acquire locks on the same resource at the same time.
--	+ A new lock to be granted must be compatible with all existing locks. If not the lock conflict ocurrs and the transaction forced to wait for all uncompatible locks to be released or timeout.
--	+ Table of compaibility of most commonly encountered lock modes (Y-yes, N-no):
--		S	U	X	IS	IX	SIX
--	S	Y	Y	N	Y	N	N
--	U	Y	N	N	Y	N	N
--	X	N	N	N	N	N	N
--	IS	Y	Y	N	Y	Y	Y
--	IX	N	N	N	Y	Y	N
--	SIX	N	N	N	Y	N	N
-- 8. LOCK ESCALTION:
--	+ Lock escalation is a process of converting many fine-grained locks into fewer coarse-grain locks.
--	+ It helps to lower the number of locks, and hence reducing system overhead and improving concurrency.
--	+ The process could be changing the intent lock on the table to the corresponding full lock (change IX lock to X lock), or escalate lower granularity lock to higer one (ex: escalate page lock to table lock).
--	+ Each escalation event operates primarily at the level of a single T-SQL statement, which means an escalation event only estimates all locks acquired on the current statement and all previous statements within a transaction.
--	+ If a lock escalation attempt fails because of conflicting locks held by other concurrent transactions, the Database Engine retries the lock escalation for each additional 1,250 locks acquired by the transaction.
--	+ If a lock escaltion succeeds, any locks operated during the event will be escalated.
--	+ With optimized locking, the number of locks acquired are reduced, and make the escalation occurs less frequently.
--	+ Lock escalation thresholds: 
--		* A lock escalation will ocurr if and only if a T-SQL statement has acquired at least 5,000 locks on a single reference of a table.
--		* The Database Engine periodically checks for possible escalations at every 1,250 newly acuired locks.
--	+ Monitor lock escalation by using the lock_escalation extended event.